### PR TITLE
rotatable markers, specific layerGroup

### PR DESCRIPTION
**Pull request by lutzer**
Added two new features: 
1. markers can be rotated by specifing the option: `rotateIcons: true`
2. only a specific layerGroup can be considered when creating the edgeMarkers by the option: `layerGroup: <someLayerGroup>`

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Very nice!! Would you mind to update the gh-pages as well?

**Comment by lutzer** [comment]
yeah, ok. i can do that later today.

**Comment by ubergesundheit** [comment]
I must say, really good work! Thanks a lot!

**Comment by lutzer** [comment]
youre welcome. :)

**Pull request merged**
