### PR TITLE
change how location of EdgeMarkers are calculated

### PR DESCRIPTION
**Pull request by kwibus**
the original just used the x or y coordinates of target.
this is close to correct. For example:
if you have EdgeMarker for a point very far away to left and bit more north.
edge maker will be placed in the corner. because both x and y are from outside screen reach.
this gives the impression that target is in direction of that corner.
but in reality it's to your left(and a small bit up)

the new implementation place marker on the intersection of line from
center of creen to target and the edge

its has small fault:
is place the marker with small offset from edge of  the screen
this offset is the height of icon for top/bottom and with for
left/right edge
this gives incorrect result if icon is not square and rotated

i tried to keep distance opacity the same but have not tested it

second commit is nor really necessary. but makes bit smoother

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Does this work with both Leaflet 0.7 and 1.0?
Can you create a screenshot or gif to show the difference?
Maybe even change the pull request so that the algorithm could be changed by the user?

**Comment by kwibus** [comment]
yes it works on 0.7 but did not tested it very well, just recreated gh-pages 0.7 version and it worked

|old|new|
|:---:|:---:|
|gh-page-old|gh-pages-new|

You can see individual edgemarker better in the  new one because the are more spread out and not all in corner.

example-zoom3

|old|new|
|:---:|:---:|
|example-old-zoom6|example-new-zoom6|
|example-old-zoom16|example-new-zoom16|

You see that in the old with the large zoom the edgemarker is in the corner, while it point relatively almost to the same latitude.

If you want i can make that pull request, but don't see why you want to have that. And it makes it a bit unnecessary complicated.
But i could breakout the location edge-marker calculation and call the function based on Boolean in options

**Comment by ubergesundheit** [comment]
thanks! very good!

**Comment by booherbg** [comment]
@kwibus ah! I see you did in fact commit theses. I didn't notice that they were merged. This one is a big help for me. Thanks, and great work!

**Pull request merged**
