### PR TITLE
Add option to set fillOpacity depending on distance

### PR DESCRIPTION
**Pull request by juliensoret**
Here is my first try. 
This modification allows the user to set a option "distanceOpacity" on true. This option makes the "fillOpacity" option dynamic and depending on the distance of the marker from the map's borders.
With this functionality added and activated, we can easily guess how far are the markers.

Here is a demo : http://kara.62.free.fr/opacityondistance/

### CODE REVIEW

**Comment by juliensoret** [comment]
Is this option worth adding in the plugin ?

**Comment by ubergesundheit** [comment]
I think you should add an option for the stroke opacity as well. Otherwise very nice!

**Comment by juliensoret** [comment]
I thought that keeping only the stroke opaque, would keep informing there are markers on the map and where.
With this modification, distanceOpacity can accept "true" and "false". I could also make it accept "fillOnly" with the current state and change "true" to include also stroke opacity. Is that a good idea?

**Comment by ubergesundheit** [comment]
Seems reasonable ;)

**Pull request merged**
