### PR TITLE
bower package

### PR DESCRIPTION
**Pull request by vko-online**

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Hi,

thanks for opening the pull request, but the url in the `bower.json` does not point to this repository..

And I think it would be unfair to the other contributors if we would omit them in the `authors` section..

If you fix these things, I would be happy to merge the pullrequest ;)

Cheers

**Comment by vko-online** [comment]
@ubergesundheit Directed to this URL, removed authors

**Comment by ubergesundheit** [comment]
Ok thanks. Can you make sure the entry over at [bower](http://bower.io/search/?q=Leaflet.EdgeMarker) will direct to this repository?

**Comment by vko-online** [comment]
@ubergesundheit 
`bower search Leaflet.EdgeMarker` ==> _https://github.com/ubergesundheit/Leaflet.EdgeMarker/_ 
`bower info Leaflet.EdgeMarker`==> _https://github.com/vko-online/Leaflet.EdgeMarker/_
Tried `bower unregister Leaflet.EdgeMarker` ==> `EFORBIDDEN: Must have push access to view repository collaborators.`

What i'm doing wrong?  Can you change it in your side?

**Comment by ubergesundheit** [comment]
I don't have bower installed. Let me check

**Comment by ubergesundheit** [comment]
In the mean time, could you try to change the bower.json back to your old repository url and then try to unregister?

**Comment by ubergesundheit** [comment]
Ok I unregistered and registered it again with the correct url. Thanks again for the PullRequest

**Comment by vko-online** [comment]
```bash
❯ bower info Leaflet.EdgeMarker
bower Leaflet.EdgeMarker#*  not-cached git://github.com/ubergesundheit/Leaflet.EdgeMarker.git#*
```


```bash
❯ bower search Leaflet.EdgeMarker
Search results:
    leaflet-edgemarker-raywalker git://github.com/raywalker-it/Leaflet.EdgeMarker-raywalker.git
    Leaflet.EdgeMarker git://github.com/ubergesundheit/Leaflet.EdgeMarker.git
```

**Comment by vko-online** [comment]
And don't forget to update README.md :+1:

**Pull request merged**
